[[actions]]
name = "play"
path = "tc2_win64.exe"
platform = "windows"
args = ["-game", "tc2", "-vulkan", "-noborder", "-particles", "1", "-precachefontchars"]

[[actions]]
name = "dx9"
path = "tc2_win64.exe"
platform = "windows"
args = ["-game", "tc2", "-noborder", "-particles", "1", "-precachefontchars"]
